"use client";
import Image from "next/image";
import { useEffect,useState } from "react";
type User={id:number;email:string;role:string;active:boolean;created_at:string};
export default function AdminUsers({currentEmail}:{currentEmail:string}){
 const [users,setUsers]=useState<User[]>([]); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [role,setRole]=useState("USER"); const [msg,setMsg]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
 async function load(){const r=await fetch('/api/admin/users',{cache:'no-store'}); const j=await r.json(); if(r.ok)setUsers(j.users||[]); else setError(j.error||'Gagal mengambil user');}
 useEffect(()=>{load()},[]);
 async function create(e:React.FormEvent){e.preventDefault();setLoading(true);setMsg('');setError('');try{const r=await fetch('/api/admin/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,role})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Gagal membuat user');setMsg('Akun berhasil dibuat.');setEmail('');setPassword('');await load();}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 return <main className="adminShell"><aside className="adminSide"><Image src="/your-aol-dashboard-logo.png" width={245} height={70} alt="logo"/><a href="/">← Kembali ke dashboard</a><div className="adminIdentity"><small>Administrator</small><b>{currentEmail}</b></div></aside><section className="adminMain"><div className="adminHeader"><div><div className="eyebrow">ACCESS MANAGEMENT</div><h1>Kelola pengguna</h1><p>Buat email dan password untuk pengguna yang boleh masuk ke aplikasi.</p></div></div><div className="adminGrid"><form className="adminCard createUser" onSubmit={create}><h2>Buat akun baru</h2><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="user@company.com"/></label><label>Password<input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimal 8 karakter"/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option value="USER">User</option><option value="ADMIN">Admin</option></select></label>{msg&&<div className="adminSuccess">{msg}</div>}{error&&<div className="loginError">{error}</div>}<button disabled={loading}>{loading?'Menyimpan...':'Buat akun'}</button></form><div className="adminCard userList"><div className="userListHead"><h2>Pengguna aplikasi</h2><span>{users.length} akun</span></div><div className="userTable">{users.map(u=><div className="userRow" key={u.id}><div className="userAvatar">{u.email[0]?.toUpperCase()}</div><div><b>{u.email}</b><small>Dibuat {new Date(u.created_at).toLocaleDateString('id-ID')}</small></div><span className={`roleBadge ${u.role.toLowerCase()}`}>{u.role}</span></div>)}</div></div></div></section></main>;
}
