"use client";
import Image from "next/image";
import { useEffect,useMemo,useState } from "react";
import {ResponsiveContainer,CartesianGrid,XAxis,YAxis,Tooltip,Legend,BarChart,Bar,PieChart,Pie,Cell} from "recharts";

type Account={no:string;name:string;accountType:string};
type Monthly={month:string;revenue:number;cogs:number;expense:number;otherIncome:number;otherExpense:number;grossProfit:number;netProfit:number};
type AuthStatus={connected:boolean;databaseConnected:boolean;user?:{name?:string;email?:string}|null;database?:{id:number;alias:string}|null;databases?:Array<{id:number;alias:string}>};
type Range={from:string;to:string};
type Menu="overview"|"connect"|"revenue"|"expenses"|"profit";
const fmt=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
const compactFmt=new Intl.NumberFormat("id-ID",{notation:"compact",maximumFractionDigits:1});
const money=(v:number)=>fmt.format(v||0),compact=(v:number)=>compactFmt.format(v||0);
function defaultRange():Range{const y=new Date().getFullYear();return{from:`${y}-01-01`,to:`${y}-12-31`}}
function ChartFilter({range,onChange,onApply,loading}:{range:Range;onChange:(r:Range)=>void;onApply:()=>void;loading?:boolean}){return <div className="chartFilter"><div className="dateField"><span>Dari</span><input type="date" value={range.from} onChange={e=>onChange({...range,from:e.target.value})}/></div><div className="dateField"><span>Sampai</span><input type="date" value={range.to} onChange={e=>onChange({...range,to:e.target.value})}/></div><button className="miniButton" onClick={onApply} disabled={loading}>{loading?"Memuat...":"Terapkan"}</button></div>}

export default function Dashboard({appUser}:{appUser:{email:string;role:string}}){
 const [menu,setMenu]=useState<Menu>("overview"),[auth,setAuth]=useState<AuthStatus|null>(null),[authError,setAuthError]=useState(""),[dbLoading,setDbLoading]=useState(false),[dataError,setDataError]=useState("");
 const [revenueRange,setRevenueRange]=useState<Range>(defaultRange()),[plRange,setPlRange]=useState<Range>(defaultRange()),[expenseRange,setExpenseRange]=useState<Range>(defaultRange());
 const [revenue,setRevenue]=useState<Monthly[]>([]),[profitLoss,setProfitLoss]=useState<Monthly[]>([]),[accounts,setAccounts]=useState<Account[]>([]),[selected,setSelected]=useState<string[]>([]),[expenses,setExpenses]=useState<Record<string,string|number>[]>([]);
 const [loadingRevenue,setLoadingRevenue]=useState(false),[loadingPL,setLoadingPL]=useState(false),[loadingExpense,setLoadingExpense]=useState(false);
 async function loadStatus(){try{const r=await fetch('/api/oauth/status',{cache:'no-store'});const j=await r.json();setAuth(j);if(j.error)setAuthError(j.error);}catch(e:any){setAuthError(e.message)}}
 useEffect(()=>{const p=new URLSearchParams(location.search);if(p.get('oauth_error'))setAuthError(p.get('oauth_error')||'');loadStatus()},[]);
 useEffect(()=>{if(auth?.databaseConnected)loadInitial()},[auth?.databaseConnected]);
 async function jsonGet(url:string){const r=await fetch(url,{cache:'no-store'});const j=await r.json();if(r.status===401){location.href='/login';throw new Error('Sesi berakhir')}if(!r.ok)throw new Error(j.error||'Gagal mengambil data');return j}
 async function selectDb(id:number){setDbLoading(true);setAuthError('');try{const r=await fetch('/api/oauth/select-db',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Gagal memilih database');await loadStatus();setMenu('overview')}catch(e:any){setAuthError(e.message)}finally{setDbLoading(false)}}
 async function loadInitial(){setLoadingRevenue(true);setLoadingPL(true);setLoadingExpense(true);setDataError('');try{const r=defaultRange();const q=new URLSearchParams({from:r.from,to:r.to});const j=await jsonGet(`/api/dashboard?${q}`);setRevenue(j.monthly||[]);setProfitLoss(j.monthly||[]);setAccounts(j.accounts||[]);setExpenses(j.expenses||[]);setSelected((j.accounts||[]).slice(0,3).map((a:Account)=>a.no))}catch(e:any){setDataError(e.message)}finally{setLoadingRevenue(false);setLoadingPL(false);setLoadingExpense(false)}}
 async function loadRevenue(){setLoadingRevenue(true);setDataError('');try{const q=new URLSearchParams(revenueRange as any);setRevenue((await jsonGet(`/api/dashboard/revenue?${q}`)).monthly||[])}catch(e:any){setDataError(e.message)}finally{setLoadingRevenue(false)}}
 async function loadPL(){setLoadingPL(true);setDataError('');try{const q=new URLSearchParams(plRange as any);setProfitLoss((await jsonGet(`/api/dashboard/profit-loss?${q}`)).monthly||[])}catch(e:any){setDataError(e.message)}finally{setLoadingPL(false)}}
 async function loadExpenses(){setLoadingExpense(true);setDataError('');try{const q=new URLSearchParams(expenseRange as any);selected.forEach(a=>q.append('account',a));const j=await jsonGet(`/api/dashboard/expenses?${q}`);setExpenses(j.expenses||[]);if(j.accounts?.length)setAccounts(j.accounts)}catch(e:any){setDataError(e.message)}finally{setLoadingExpense(false)}}
 const revenueTotal=useMemo(()=>revenue.reduce((s,r)=>s+r.revenue,0),[revenue]);const plTotals=useMemo(()=>profitLoss.reduce((s,r)=>({gross:s.gross+r.grossProfit,net:s.net+r.netProfit}),{gross:0,net:0}),[profitLoss]);
 const expenseColors=["#f43f5e","#8b5cf6","#0ea5e9","#10b981","#f59e0b","#6366f1","#ec4899","#14b8a6"];
 const expensePieData=useMemo(()=>selected.slice(0,8).map((no,i)=>({name:accounts.find(a=>a.no===no)?.name||no,value:expenses.reduce((sum,row)=>sum+Number(row[no]||0),0),fill:expenseColors[i%expenseColors.length]})).filter(x=>x.value!==0),[selected,accounts,expenses]);
 const connected=Boolean(auth?.databaseConnected);
 const menuItems:[Menu,string,string][]=[["overview","Overview","⌁"],["connect","Koneksi Accurate","⛓"],["revenue","Omzet Bulanan","↗"],["expenses","Biaya Bulanan","▥"],["profit","Laba Rugi","◆"]];
 function toggle(no:string){setSelected(p=>p.includes(no)?p.filter(x=>x!==no):[...p,no])}
 async function logout(){await fetch('/api/auth/logout',{method:'POST'});location.href='/login'}
 async function disconnect(){await fetch('/api/oauth/disconnect',{method:'POST'});setAuth(null);await loadStatus();setMenu('connect')}
 if(!auth)return <main className="loadingPage"><div className="spinner"/><p>Menyiapkan dashboard...</p></main>;
 return <main className="appShell"><aside className="sidebar"><Image src="/aol-insight-logo.png" width={300} height={118} alt="AOL Insight" className="sideLogo" priority/><nav>{menuItems.map(([id,label,icon])=><button key={id} onClick={()=>setMenu(id)} className={`navItem ${menu===id?'active':''}`}><span>{icon}</span>{label}</button>)}{appUser.role==='ADMIN'&&<a href="/admin" className="navItem"><span>⚙</span>Kelola User</a>}</nav><div className="sidebarBottom">{connected?<div className="dbPill"><span className="dbDot"/><div><small>Database Accurate</small><b>{auth.database?.alias}</b></div></div>:<div className="dbPill offline"><span className="dbDot"/><div><small>Accurate Online</small><b>Belum terhubung</b></div></div>}<button className="logoutBtn" onClick={logout}>Keluar dari aplikasi</button></div></aside>
 <section className="mainPanel"><header className="topbar"><div><div className="eyebrow">AOL INSIGHT</div><h1>{menu==='overview'?'Dashboard':menu==='connect'?'Koneksi Accurate':menu==='revenue'?'Omzet per Bulan':menu==='expenses'?'Biaya per Bulan':'Laba Rugi per Bulan'}</h1><p>{connected?`Terhubung ke ${auth.database?.alias}.`:'Hubungkan Accurate Online untuk mulai membaca data.'}</p></div><div className="userChip"><div className="avatar">{appUser.email[0]?.toUpperCase()}</div><div><b>{appUser.email}</b><small>{appUser.role}</small></div></div></header>
 {dataError&&<div className="notice errorNotice dataNotice"><b>Data belum berhasil dibaca.</b><span>{dataError}</span></div>}
 {menu==='connect'&&<section className="modernCard connectionPageCard"><div className="connectionHero"><div><span className={`statusPill ${connected?'online':''}`}>{connected?'● Connected':'○ Not connected'}</span><h2>Koneksi ke Accurate Online</h2><p>OAuth digunakan untuk memberikan akses baca ke akun perkiraan dan jurnal umum. Password Accurate tidak disimpan di aplikasi ini.</p></div><div className="oauthMark">A</div></div>{authError&&<div className="notice errorNotice">{authError}</div>}{!auth.connected?<a href="/api/oauth/connect" className="connectButton compactConnect"><span>Connect Accurate Online</span><span>→</span></a>:!auth.databaseConnected?<div className="dbChooser"><h3>Pilih database</h3>{(auth.databases||[]).map(db=><button key={db.id} disabled={dbLoading} onClick={()=>selectDb(db.id)} className="dbItem"><span className="dbIcon">▦</span><span><b>{db.alias}</b><small>Database ID {db.id}</small></span><span>→</span></button>)}</div>:<div className="connectedInfo"><div><small>Database aktif</small><strong>{auth.database?.alias}</strong></div><button onClick={disconnect}>Putuskan koneksi</button></div>}</section>}
 {menu!=='connect'&&!connected&&<section className="emptyState modernCard"><div className="emptyIcon">⛓</div><h2>Accurate Online belum terhubung</h2><p>Hubungkan akun Accurate terlebih dahulu agar grafik dapat ditampilkan.</p><button onClick={()=>setMenu('connect')}>Buka menu Koneksi Accurate →</button></section>}
 {connected&&menu==='overview'&&<><section className="summaryGrid"><div className="metricCard accent"><div className="metricTop"><span>Total Omzet</span><span className="metricIcon">↗</span></div><strong>{money(revenueTotal)}</strong><small>periode grafik omzet</small></div><div className="metricCard"><div className="metricTop"><span>Laba Kotor</span><span className="metricIcon">◎</span></div><strong>{money(plTotals.gross)}</strong><small>periode laba rugi</small></div><div className="metricCard"><div className="metricTop"><span>Laba Bersih</span><span className="metricIcon">◆</span></div><strong>{money(plTotals.net)}</strong><small>periode laba rugi</small></div></section><section className="overviewGrid"><button className="overviewTile" onClick={()=>setMenu('revenue')}><span>↗</span><div><b>Omzet per Bulan</b><small>Lihat tren pendapatan</small></div><em>→</em></button><button className="overviewTile" onClick={()=>setMenu('expenses')}><span>▥</span><div><b>Biaya per Bulan</b><small>Pilih akun biaya</small></div><em>→</em></button><button className="overviewTile" onClick={()=>setMenu('profit')}><span>◆</span><div><b>Laba Rugi</b><small>Revenue, gross & net profit</small></div><em>→</em></button></section></>}
 {connected&&menu==='revenue'&&<section className="chartCard modernCard fullCard"><div className="cardHead"><div><span className="cardKicker">REVENUE</span><h2>Total Omzet per Bulan</h2><p>Akun REVENUE: credit − debit.</p></div><ChartFilter range={revenueRange} onChange={setRevenueRange} onApply={loadRevenue} loading={loadingRevenue}/></div><div className="chartWrap"><ResponsiveContainer width="100%" height={390}><BarChart data={revenue} barCategoryGap="28%"><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="month" tickLine={false} axisLine={false}/><YAxis tickFormatter={compact} tickLine={false} axisLine={false}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Bar dataKey="revenue" name="Omzet" fill="#f43f5e" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></div></section>}
 {connected&&menu==='profit'&&<section className="chartCard modernCard fullCard"><div className="cardHead"><div><span className="cardKicker">PROFITABILITY</span><h2>Laba Rugi per Bulan</h2><p>Revenue, laba kotor, dan laba bersih dari klasifikasi akun jurnal.</p></div><ChartFilter range={plRange} onChange={setPlRange} onApply={loadPL} loading={loadingPL}/></div><div className="chartWrap"><ResponsiveContainer width="100%" height={390}><BarChart data={profitLoss} barGap={5}><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="month" tickLine={false} axisLine={false}/><YAxis tickFormatter={compact} tickLine={false} axisLine={false}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Legend/><Bar dataKey="revenue" name="Revenue" fill="#f43f5e" radius={[7,7,0,0]}/><Bar dataKey="grossProfit" name="Laba Kotor" fill="#8b5cf6" radius={[7,7,0,0]}/><Bar dataKey="netProfit" name="Laba Bersih" fill="#111827" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></div></section>}
 {connected&&menu==='expenses'&&<section className="chartCard modernCard fullCard"><div className="cardHead"><div><span className="cardKicker">EXPENSES</span><h2>Biaya per Bulan</h2><p>Pilih akun EXPENSE / OTHER_EXPENSE yang ingin dibandingkan.</p></div><ChartFilter range={expenseRange} onChange={setExpenseRange} onApply={loadExpenses} loading={loadingExpense}/></div><div className="expenseBody"><div className="accountPicker"><div className="pickerHead"><b>Akun biaya</b><span>{selected.length} dipilih</span></div><div className="accountScroll">{accounts.map(a=><label key={a.no} className={`accountRow ${selected.includes(a.no)?'selected':''}`}><input type="checkbox" checked={selected.includes(a.no)} onChange={()=>toggle(a.no)}/><span className="checkVisual">✓</span><span><b>{a.name}</b><small>{a.no} · {a.accountType}</small></span></label>)}</div><button className="applyAccount" onClick={loadExpenses} disabled={loadingExpense}>{loadingExpense?'Memuat...':'Tampilkan akun terpilih'}</button></div><div className="expenseVisuals"><div className="expenseChart"><h3>Perbandingan per Bulan</h3><ResponsiveContainer width="100%" height={310}><BarChart data={expenses} barGap={4}><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="month" tickLine={false} axisLine={false}/><YAxis tickFormatter={compact} tickLine={false} axisLine={false}/><Tooltip formatter={(v:any)=>money(Number(v))}/><Legend/>{selected.slice(0,8).map((no,i)=><Bar key={no} dataKey={no} name={accounts.find(a=>a.no===no)?.name||no} fill={expenseColors[i%expenseColors.length]} radius={[6,6,0,0]}/>)}</BarChart></ResponsiveContainer></div><div className="expensePie"><h3>Komposisi Biaya</h3>{expensePieData.length?<ResponsiveContainer width="100%" height={310}><PieChart><Pie data={expensePieData} dataKey="value" nameKey="name" cx="50%" cy="46%" innerRadius={62} outerRadius={105} paddingAngle={2}>{expensePieData.map((entry,i)=><Cell key={`${entry.name}-${i}`} fill={entry.fill}/>)}</Pie><Tooltip formatter={(v:any)=>money(Number(v))}/><Legend verticalAlign="bottom" height={44}/></PieChart></ResponsiveContainer>:<div className="pieEmpty">Pilih akun biaya yang memiliki transaksi pada periode ini.</div>}</div></div></div></section>}
 <footer className="footer">AOL Insight · Accurate Online OAuth 2.0</footer></section></main>
}
